version: '3.8'

services:
  aymara-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aymara-api
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3